name: 'build'
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build_conda:
    name: RAMP tests
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: anaconda-client-env
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: false
      - run: |
          export RAMP_TEST_MODE=true  # to have download_data.py just download the dummy dataset
          python download_data.py
          ramp-test --quick-test
  build_pip:
    name: Linux pip
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 nbconvert[test]
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install git+https://github.com/AlexandreHutton/stroke
    - name: Test
      run: |
        flake8 *.py submissions/*/*.py
        export RAMP_TEST_MODE=true  # to have download_data.py just download the dummy dataset
        python download_data.py
        ramp-test --quick-test
        ramp-test --submission sample --quick-test
        jupyter nbconvert --execute stroke_lesions_starting_kit.ipynb --to html --ExecutePreprocessor.kernel_name=python3 
